language: groovy
sudo: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew cobertura
  - ./gradlew sonarqube -Dsonar.host.url=$sonar_host -Dsonar.login=$sonar_login
after_success:
  - bash <(curl -s https://codecov.io/bash)