language: groovy
sudo: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
matrix:
  include:
  - jdk: openjdk7
    env: ONLY_CHECK='true'
  - jdk: oraclejdk7
    env: ONLY_CHECK='true'
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_script:
  - chmod +x gradlew
script: ./travis.sh
